
version: 2

sources:
  - name: main_db
    database: analytics  
    schema: analytics
    tables:
      - name: subscriptions
      - name: subscription_plans

models:
  - name: stg_maindb__subscriptions
    description: "Staging model for subscriptions table from main database"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: plan_id
        description: "ID of the subscription plan tied to this subscription"
        tests:
          - not_null
      - name: workspace_id
        description: "ID of the workspace this subscription belongs to"
        tests:
          - not_null
      - name: created_at
        description: "Subscription creation timestamp"
        tests:
          - not_null
      - name: created_date
        description: "Subscription creation date"
        tests:
          - not_null
      - name: updated_at
        description: "Subscription last update timestamp"
        tests:
          - not_null
      - name: updated_date
        description: "Subscription last update date"
        tests:
          - not_null
      - name: deleted_at
        description: "Subscription deletion timestamp"
      - name: deleted_date
        description: "Subscription deletion date"

  - name: stg_maindb__subscription_plans
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: name
        description: "Subscription plan name"
        tests:
          - unique
          - not_null
      - name: price
        description: "Subscription plan price amount in USD"
        tests:
          - not_null
      - name: price_cents
        description: "Subscription plan price amount in cents"
        tests:
          - not_null
      - name: created_at
        description: "Subscription plan creation timestamp"
        tests:
          - not_null
      - name: created_date
        description: "Subscription plan creation date"
        tests:
          - not_null
      - name: updated_at
        description: "Subscription plan last update timestamp"
        tests:
          - not_null
      - name: updated_date
        description: "Subscription plan last update date"
        tests:
          - not_null
      - name: deleted_at
        description: "Subscription plan deletion timestamp"
      - name: deleted_date
        description: "Subscription plan deletion date"