version: '3.1'

services:

  metabase:
    build: .
    image: metabase-with-clickhouse_m1_compatible
    ports:
      - "3001:3000"
    volumes:
      - ./plugins/ch.jar:/app/plugins/clickhouse.jar
      - ./metabase.db:/app/metabase.db
