version: '3.1'

services:

  metabase:
    build: .
    image: metabase-with-clickhouse_m1_compatible
    ports:
      - "3001:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./plugins/ch.jar:/app/plugins/clickhouse.jar
      - ~/metabase-data:/metabase-data
